INSERT INTO `lookups` (`name`, `ru`, `code`, `type`, `ord`) VALUES
('Седан', 'Седан', '1', 'bodyType', 1),
('Универсал', 'Универсал', '2', 'bodyType', 2),
('Хэтчбек', 'Хэтчбек', '3', 'bodyType', 3),
('Минивэн', 'Минивэн', '4', 'bodyType', 4),
('Компактвэн', 'Компактвэн', '5', 'bodyType', 5),
('Микровэн', 'Микровэн', '6', 'bodyType', 6),
('Кроссовер', 'Кроссовер', '7', 'bodyType', 7),
('Внедорожник', 'Внедорожник', '8', 'bodyType', 8),
('Пикап', 'Пикап', '9', 'bodyType', 9),
('Купе', 'Купе', '10', 'bodyType', 10),
('Кабриолет', 'Кабриолет', '11', 'bodyType', 11),
('Родстер', 'Родстер', '12', 'bodyType', 12),
('Лимузин', 'Лимузин', '13', 'bodyType', 13),
('Микроавтобус', 'Микроавтобус', '14', 'bodyType', 14),
('Фургон', 'Фургон', '15', 'bodyType', 15),
('Грузовик', 'Грузовик', '16', 'bodyType', 16),
('Грузовой фургон', 'Грузовой фургон', '17', 'bodyType', 17),
('УПВ', 'УПВ', '18', 'bodyType', 18),
('Тарга', 'Тарга', '19', 'bodyType', 19),
('Купе-кабриолет', 'Купе-кабриолет', '20', 'bodyType', 20),
('Ландоле', 'Ландоле', '21', 'bodyType', 21),


('Белый', '', '1', 'color', 1),
('Черный', '', '2', 'color', 2),
('Комбинированный', '', '3', 'color', 0),
('Бензин', '', '1', 'engineType', 1),
(' - Бензин инжектор', '', '2', 'engineType', 2),
(' - Бензин карбюратор', '', '3', 'engineType', 3),
(' - Бензин ротор', '', '4', 'engineType', 4),
(' - Бензин компрессор', '', '5', 'engineType', 5),
(' - Бензин турбонаддув', '', '6', 'engineType', 6),
('Дизель', '', '7', 'engineType', 7),
(' - Дизель', '', '8', 'engineType', 8),
(' - Дизель турбонаддув', '', '9', 'engineType', 9),
('Гибрид', '', '10', 'engineType', 10),
(' - Гибридный бензиновый', '', '11', 'engineType', 11),
(' - Гибридный дизельный', '', '12', 'engineType', 12),
('Передний', '', '1', 'driveType', 1),
('Задний', '', '2', 'driveType', 2),
('Полный', '', '3', 'driveType', 3),
('Механическая', '', '1', 'transmissionType', 1),
('Автомат', '', '2', 'transmissionType', 2),
(' - АКПП', '', '3', 'transmissionType', 3),
(' - Вариатор', '', '4', 'transmissionType', 4),
(' - Робот', '', '5', 'transmissionType', 5),
('Левый', '', '1', 'steeringWheelPosition', 1),
('Правый', '', '2', 'steeringWheelPosition', 2),
('Новый', '', '1', 'carState', 1),
('Отличное', '', '2', 'carState', 2),
('Хорошее', '', '3', 'carState', 3),
('Среднее ', '', '4', 'carState', 4),
('Не на ходу, требует ремонта', '', '6', 'carState', 6),
('После аварии', '', '7', 'carState', 7),
('Плохое', '', '5', 'carState', 5),
('Растоможен', '', '1', 'customState', 1),
('Не растоможен', '', '2', 'customState', 2),
('Нет', '', '1', 'OwnersCount', 1),
('Один', '', '2', 'ownersCount', 2),
('Два', '', '3', 'ownersCount', 3),
('Три', '', '4', 'ownersCount', 4),
('Более трёх', '', '5', 'ownersCount', 5),
('Есть', '', '1', 'airConditionerType', 1),
('Климат-контроль, 1-зона', '', '2', 'airConditionerType', 2),
('Климат-контроль, 2-зоны', '', '3', 'airConditionerType', 3),
('Климат-контроль, 3-зоны и более', '', '4', 'airConditionerType', 4),
('Кассетная магнитола', '', 'cassette', 'multimediaType', 1),
('Аудио CD', '', 'cd', 'multimediaType', 2),
('CD mp3', '', 'mp3', 'multimediaType', 3),
('DVD', '', 'dvd', 'multimediaType', 4),
('USB', '', 'usb', 'multimediaType', 5),
('AUX', '', 'aux', 'multimediaType', 6),
('Навигация', '', 'navi', 'multimediaType', 7),
('TV-тюнер', '', 'tv', 'multimediaType', 8),
('Сабвуфер', '', 'sub', 'multimediaType', 9),
('CD-чейнджер', '', 'changer', 'multimediaType', 10),
('Водительская', '', '1', 'airbagsPlacement', 1),
('Фронтальные', '', '2', 'airbagsPlacement', 2),
('Фронтальные и боковые', '', '3', 'airbagsPlacement', 3),
('По высоте', '', '1', 'driversSeatAdjustment', 1),
('Электропривод', '', '2', 'driversSeatAdjustment', 2),
('Электропривод с памятью', '', '3', 'driversSeatAdjustment', 3),
('В одной плоскости', '', '1', 'tiltWheelAdjustment', 1),
('В двух плоскостях', '', '2', 'tiltWheelAdjustment', 2),
('Электропривод', '', '3', 'tiltWheelAdjustment', 3),
('Ткань', '', '1', 'interiorType', 1),
('Велюр', '', '2', 'interiorType', 2),
('Комбинированный', '', '3', 'interiorType', 3),
('Кожа', '', '4', 'interiorType', 4),
('Здание стекла', '', '1', 'TintType', 1),
('По кругу', '', '2', 'tintType', 2),
('Гидро', '', '1', 'powerSteeringType', 1),
('Электро', '', '2', 'powerSteeringType', 2),
('Передние', '', '1', 'windowRaiserType', 1),
('Все', '', '2', 'windowRaiserType', 2),

(140, 'Article', 'Статья', '1', 'ObjectType', 1),
(141, 'Video', 'Видео', '2', 'ObjectType', 2),
(142, 'Blog', 'Блог', '3', 'ObjectType', 3),
(143, 'Brand', 'Бренд', '4', 'ObjectType', 4),
(144, 'Family', 'Модельный ряд', '5', 'ObjectType', 5),
(145, 'Car', 'Модель', '6', 'ObjectType', 6),
(146, 'Modification', 'Модификация', '7', 'ObjectType', 7),
(147, 'Gallery', 'Галерея', '8', 'ObjectType', 8),
(148, 'Workshop', 'Тюнинг ателье', '9', 'ObjectType', 8),
(149, 'User', 'Пользователь', '10', 'ObjectType', 10),
(150, 'Post', 'Запись в блоге', '11', 'ObjectType', 11),
(151, 'History', 'История марок', '12', 'ObjectType', 12),
(152, 'Comment', 'Комментарий', '13', 'ObjectType', 13);